baseURL = "https://sean-mcnabb.net/"
languageCode = "en-us"
title = "Sean McNabb's Site"
theme = "coder"

[pagination]
pagerSize = 5

[params]
author = "Sean McNabb"
description = "Sean McNabb's Personal Website"
info = "Software developer, writer"
colorScheme = "auto"
keywords = "blog,developer,personal,professional"
hideColorSchemeToggle = false
gravatar = "sean.mcnabb.83@gmail.com"

[[params.social]]
name = "linkedin"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/sean-mcnabb-2b767544/"

[[params.social]]
name = "github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/smcnabb83"


[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/resume"

[[languages.en.menu.main]]
name = "Blog"
weight = 1
url = "posts/"